In [10]:
import pandas as pd
import random
from datetime import datetime

In [4]:
some_dict = {
    'students': ['Claire', 'Marc', 'Rick', 'Julien', 'Amos'],
    'dankedy': [19, 2, 1012, -12, 31] 
}

In [6]:
df = pd.DataFrame(some_dict)
df

   dankedy students
0       19   Claire
1        2     Marc
2     1012     Rick
3      -12   Julien
4       31     Amos

In [7]:
df['dankedy']

0      19
1       2
2    1012
3     -12
4      31
Name: dankedy, dtype: int64

In [8]:
type(_)

pandas.core.series.Series

In [9]:
pd.Series([random.randint(0,50) for x in range(10)])

0     9
1    22
2     7
3    40
4    38
5    48
6    40
7    12
8     7
9    46
dtype: int64

In [28]:
fmt = '%b %d, %Y'
finances = {
    "Name": ["Pablo", "Marcel", "Lisa", "Joanne", "Gerry", 'Billy'],
    "Assets": [120000, 80000, 110000, 230000, 1000000, 1200],
    "Debts": [90000, 80000, 30000, 50000, 800000, 10],
    "Updated": [
    datetime.strptime("Jun 10, 2011", fmt),
    datetime.strptime("Dec 30, 2005", fmt),
    datetime.strptime("May 4, 2000", fmt),
    datetime.strptime("Feb 16, 2007", fmt),
    datetime.strptime("Feb 16, 2007", fmt),
    datetime.strptime("Feb 16, 2007", fmt),
    ],
    "Total Rating": [3.5, 2.5, 4.0, 5.0, 4.0, 5.0]
}

In [29]:
df = pd.DataFrame(finances)

In [30]:
df.Name

0     Pablo
1    Marcel
2      Lisa
3    Joanne
4     Gerry
5     Billy
Name: Name, dtype: object

In [31]:
df.iloc[0]

Assets                       120000
Debts                         90000
Name                          Pablo
Total Rating                    3.5
Updated         2011-06-10 00:00:00
Name: 0, dtype: object

In [32]:
df.columns

Index(['Assets', 'Debts', 'Name', 'Total Rating', 'Updated'], dtype='object')

In [33]:
df[['Debts', "Assets"]]

    Debts   Assets
0   90000   120000
1   80000    80000
2   30000   110000
3   50000   230000
4  800000  1000000
5      10     1200

In [34]:
df[df.Debts > 50000]

    Assets   Debts    Name  Total Rating    Updated
0   120000   90000   Pablo           3.5 2011-06-10
1    80000   80000  Marcel           2.5 2005-12-30
4  1000000  800000   Gerry           4.0 2007-02-16

In [35]:
df[df.Debts < 50000]

   Assets  Debts   Name  Total Rating    Updated
2  110000  30000   Lisa           4.0 2000-05-04
5    1200     10  Billy           5.0 2007-02-16

In [43]:
df = pd.read_csv('boston_housing_data.csv', sep=',', header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,0.00632,18.0,2.31,0.000,0.538,6.575,65.2000,4.0900,1.0,296.0,15.30,396.90,4.98,24.0
1,NaN,0.02731,0.0,7.07,0.000,0.469,6.421,78.9000,4.9671,2.0,242.0,17.80,396.90,9.14,21.6
2,NaN,0.02729,0.0,7.07,0.000,0.469,7.185,61.1000,4.9671,2.0,242.0,17.80,392.83,4.03,34.7
3,NaN,0.03237,0.0,2.18,0.000,0.458,6.998,45.8000,6.0622,3.0,222.0,18.70,394.63,2.94,33.4
4,NaN,0.06905,0.0,2.18,0.000,0.458,7.147,54.2000,6.0622,3.0,222.0,18.70,396.90,5.33,36.2
5,NaN,0.02985,0.0,2.18,0.000,0.458,6.430,58.7000,6.0622,3.0,222.0,18.70,394.12,5.21,28.7
6,NaN,0.08829,12.5,7.87,0.000,0.524,6.012,66.6000,5.5605,5.0,311.0,15.20,395.60,12.43,22.9
7,NaN,0.14455,12.5,7.87,0.000,0.524,6.172,96.1000,5.9505,5.0,311.0,15.20,396.90,19.15,27.1
8,NaN,0.21124,12.5,7.87,0.000,0.524,5.631,100.0000,6.0821,5.0,311.0,15.20,386.63,29.93,16.5
9,NaN,0.17004,12.5,7.87,0.000,0.524,6.004,85.9000,6.5921,5.0,311.0,15.20,386.71,17.10,18.9
10,NaN,0.22489,12.5,7.87,0.000,0.524,6.377,94.3000,6.3467,5.0,311.0,15.20,392.52,20.45,15.0
11,NaN,0.11747,12.5,7.87,0.000,0.524,6.009,82.9000,6.2267,5.0,311.0,15.20,396.90,13.27,18.9
12,NaN,0.09378,12.5,7.87,0.000,0.524,5.889,39.0000,5.4509,5.0,311.0,15.20,390.50,15.71,21.7
13,NaN,0.62976,0.0,8.14,0.000,0.538,5.949,61.8000,4.7075,4.0,307.0,21.00,396.90,8.26,20.4
14,NaN,0.63796,0.0,8.14,0.000,0.538,6.096,84.5000,4.4619,4.0,307.0,21.00,380.02,10.26,18.2
15,NaN,0.62739,0.0,8.14,0.000,0.538,5.834,56.5000,4.4986,4.0,307.0,21.00,395.62,8.47,19.9
16,NaN,1.05393,0.0,8.14,0.000,0.538,5.935,29.3000,4.4986,4.0,307.0,21.00,386.85,6.58,23.1
17,NaN,0.78420,0.0,8.14,0.000,0.538,5.990,81.7000,4.2579,4.0,307.0,21.00,386.75,14.67,17.5
18,NaN,0.80271,0.0,8.14,0.000,0.538,5.456,36.6000,3.7965,4.0,307.0,21.00,288.99,11.69,20.2
19,NaN,0.72580,0.0,8.14,0.000,0.538,5.727,69.5000,3.7965,4.0,307.0,21.00,390.95,11.28,18.2
20,NaN,1.25179,0.0,8.14,0.000,0.538,5.570,98.1000,3.7979,4.0,307.0,21.00,376.57,21.02,13.6
21,NaN,0.85204,0.0,8.14,0.000,0.538,5.965,89.2000,4.0123,4.0,307.0,21.00,392.53,13.83,19.6
22,NaN,1.23247,0.0,8.14,0.000,0.538,6.142,91.7000,3.9769,4.0,307.0,21.00,396.90,18.72,15.2
23,NaN,0.98843,0.0,8.14,0.000,0.538,5.813,100.0000,4.0952,4.0,307.0,21.00,394.54,19.88,14.5
24,NaN,0.75026,0.0,8.14,0.000,0.538,5.924,94.1000,4.3996,4.0,307.0,21.00,394.33,16.30,15.6
25,NaN,0.84054,0.0,8.14,0.000,0.538,5.599,85.7000,4.4546,4.0,307.0,21.00,303.42,16.51,13.9
26,NaN,0.67191,0.0,8.14,0.000,0.538,5.813,90.3000,4.6820,4.0,307.0,21.00,376.88,14.81,16.6
27,NaN,0.95577,0.0,8.14,0.000,0.538,6.047,88.8000,4.4534,4.0,307.0,21.00,306.38,17.28,14.8
28,NaN,0.77299,0.0,8.14,0.000,0.538,6.495,94.4000,4.4547,4.0,307.0,21.00,387.94,12.80,18.4
29,NaN,1.00245,0.0,8.14,0.000,0.538,6.674,87.3000,4.2390,4.0,307.0,21.00,380.23,11.98,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,NaN,4.87141,0.0,18.10,0.000,0.614,6.484,93.6000,2.3053,24.0,666.0,20.20,396.21,18.68,16.7
477,15.0234,0.00000,18.1,0.00,0.614,5.304,97.300,2.1007,24.0000,666.0,20.2,349.48,24.91,12.00,NaN
478,10.2330,0.00000,18.1,0.00,0.614,6.185,96.700,2.1705,24.0000,666.0,20.2,379.70,18.03,14.60,NaN
479,14.3337,0.00000,18.1,0.00,0.614,6.229,88.000,1.9512,24.0000,666.0,20.2,383.32,13.11,21.40,NaN
480,NaN,5.82401,0.0,18.10,0.000,0.532,6.242,64.7000,3.4242,24.0,666.0,20.20,396.90,10.74,23.0
481,NaN,5.70818,0.0,18.10,0.000,0.532,6.750,74.9000,3.3317,24.0,666.0,20.20,393.07,7.74,23.7
482,NaN,5.73116,0.0,18.10,0.000,0.532,7.061,77.0000,3.4106,24.0,666.0,20.20,395.28,7.01,25.0
483,NaN,2.81838,0.0,18.10,0.000,0.532,5.762,40.3000,4.0983,24.0,666.0,20.20,392.92,10.42,21.8
484,NaN,2.37857,0.0,18.10,0.000,0.583,5.871,41.9000,3.7240,24.0,666.0,20.20,370.73,13.34,20.6
485,NaN,3.67367,0.0,18.10,0.000,0.583,6.312,51.9000,3.9917,24.0,666.0,20.20,388.62,10.58,21.2
486,NaN,5.69175,0.0,18.10,0.000,0.583,6.114,79.8000,3.5459,24.0,666.0,20.20,392.68,14.98,19.1
487,NaN,4.83567,0.0,18.10,0.000,0.583,5.905,53.2000,3.1523,24.0,666.0,20.20,388.22,11.45,20.6
488,NaN,0.15086,0.0,27.74,0.000,0.609,5.454,92.7000,1.8209,4.0,711.0,20.10,395.09,18.06,15.2
489,NaN,0.18337,0.0,27.74,0.000,0.609,5.414,98.3000,1.7554,4.0,711.0,20.10,344.05,23.97,7.0
490,NaN,0.20746,0.0,27.74,0.000,0.609,5.093,98.0000,1.8226,4.0,711.0,20.10,318.43,29.68,8.1
491,NaN,0.10574,0.0,27.74,0.000,0.609,5.983,98.8000,1.8681,4.0,711.0,20.10,390.11,18.07,13.6
492,NaN,0.11132,0.0,27.74,0.000,0.609,5.983,83.5000,2.1099,4.0,711.0,20.10,396.90,13.35,20.1
493,NaN,0.17331,0.0,9.69,0.000,0.585,5.707,54.0000,2.3817,6.0,391.0,19.20,396.90,12.01,21.8
494,NaN,0.27957,0.0,9.69,0.000,0.585,5.926,42.6000,2.3817,6.0,391.0,19.20,396.90,13.59,24.5
495,NaN,0.17899,0.0,9.69,0.000,0.585,5.670,28.8000,2.7986,6.0,391.0,19.20,393.29,17.60,23.1
496,NaN,0.28960,0.0,9.69,0.000,0.585,5.390,72.9000,2.7986,6.0,391.0,19.20,396.90,21.14,19.7
497,NaN,0.26838,0.0,9.69,0.000,0.585,5.794,70.6000,2.8927,6.0,391.0,19.20,396.90,14.10,18.3
498,NaN,0.23912,0.0,9.69,0.000,0.585,6.019,65.3000,2.4091,6.0,391.0,19.20,396.90,12.92,21.2
499,NaN,0.17783,0.0,9.69,0.000,0.585,5.569,73.5000,2.3999,6.0,391.0,19.20,395.77,15.10,17.5
500,NaN,0.22438,0.0,9.69,0.000,0.585,6.027,79.7000,2.4982,6.0,391.0,19.20,396.90,14.33,16.8
501,NaN,0.06263,0.0,11.93,0.000,0.573,6.593,69.1000,2.4786,1.0,273.0,21.00,391.99,9.67,22.4
502,NaN,0.04527,0.0,11.93,0.000,0.573,6.120,76.7000,2.2875,1.0,273.0,21.00,396.90,9.08,20.6
503,NaN,0.06076,0.0,11.93,0.000,0.573,6.976,91.0000,2.1675,1.0,273.0,21.00,396.90,5.64,23.9
504,NaN,0.10959,0.0,11.93,0.000,0.573,6.794,89.3000,2.3889,1.0,273.0,21.00,393.45,6.48,22.0
505,NaN,0.04741,0.0,11.93,0.000,0.573,6.030,80.8000,2.5050,1.0,273.0,21.00,396.90,7.88,11.9

In [50]:
df.rename(columns={0:'NaN_col'}).drop('NaN_col', axis=1)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.00632,18.0,2.31,0.000,0.538,6.575,65.2000,4.0900,1.0,296.0,15.30,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.000,0.469,6.421,78.9000,4.9671,2.0,242.0,17.80,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.000,0.469,7.185,61.1000,4.9671,2.0,242.0,17.80,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.000,0.458,6.998,45.8000,6.0622,3.0,222.0,18.70,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.000,0.458,7.147,54.2000,6.0622,3.0,222.0,18.70,396.90,5.33,36.2
5,0.02985,0.0,2.18,0.000,0.458,6.430,58.7000,6.0622,3.0,222.0,18.70,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.000,0.524,6.012,66.6000,5.5605,5.0,311.0,15.20,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.000,0.524,6.172,96.1000,5.9505,5.0,311.0,15.20,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.000,0.524,5.631,100.0000,6.0821,5.0,311.0,15.20,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.000,0.524,6.004,85.9000,6.5921,5.0,311.0,15.20,386.71,17.10,18.9
10,0.22489,12.5,7.87,0.000,0.524,6.377,94.3000,6.3467,5.0,311.0,15.20,392.52,20.45,15.0
11,0.11747,12.5,7.87,0.000,0.524,6.009,82.9000,6.2267,5.0,311.0,15.20,396.90,13.27,18.9
12,0.09378,12.5,7.87,0.000,0.524,5.889,39.0000,5.4509,5.0,311.0,15.20,390.50,15.71,21.7
13,0.62976,0.0,8.14,0.000,0.538,5.949,61.8000,4.7075,4.0,307.0,21.00,396.90,8.26,20.4
14,0.63796,0.0,8.14,0.000,0.538,6.096,84.5000,4.4619,4.0,307.0,21.00,380.02,10.26,18.2
15,0.62739,0.0,8.14,0.000,0.538,5.834,56.5000,4.4986,4.0,307.0,21.00,395.62,8.47,19.9
16,1.05393,0.0,8.14,0.000,0.538,5.935,29.3000,4.4986,4.0,307.0,21.00,386.85,6.58,23.1
17,0.78420,0.0,8.14,0.000,0.538,5.990,81.7000,4.2579,4.0,307.0,21.00,386.75,14.67,17.5
18,0.80271,0.0,8.14,0.000,0.538,5.456,36.6000,3.7965,4.0,307.0,21.00,288.99,11.69,20.2
19,0.72580,0.0,8.14,0.000,0.538,5.727,69.5000,3.7965,4.0,307.0,21.00,390.95,11.28,18.2
20,1.25179,0.0,8.14,0.000,0.538,5.570,98.1000,3.7979,4.0,307.0,21.00,376.57,21.02,13.6
21,0.85204,0.0,8.14,0.000,0.538,5.965,89.2000,4.0123,4.0,307.0,21.00,392.53,13.83,19.6
22,1.23247,0.0,8.14,0.000,0.538,6.142,91.7000,3.9769,4.0,307.0,21.00,396.90,18.72,15.2
23,0.98843,0.0,8.14,0.000,0.538,5.813,100.0000,4.0952,4.0,307.0,21.00,394.54,19.88,14.5
24,0.75026,0.0,8.14,0.000,0.538,5.924,94.1000,4.3996,4.0,307.0,21.00,394.33,16.30,15.6
25,0.84054,0.0,8.14,0.000,0.538,5.599,85.7000,4.4546,4.0,307.0,21.00,303.42,16.51,13.9
26,0.67191,0.0,8.14,0.000,0.538,5.813,90.3000,4.6820,4.0,307.0,21.00,376.88,14.81,16.6
27,0.95577,0.0,8.14,0.000,0.538,6.047,88.8000,4.4534,4.0,307.0,21.00,306.38,17.28,14.8
28,0.77299,0.0,8.14,0.000,0.538,6.495,94.4000,4.4547,4.0,307.0,21.00,387.94,12.80,18.4
29,1.00245,0.0,8.14,0.000,0.538,6.674,87.3000,4.2390,4.0,307.0,21.00,380.23,11.98,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.000,0.614,6.484,93.6000,2.3053,24.0,666.0,20.20,396.21,18.68,16.7
477,0.00000,18.1,0.00,0.614,5.304,97.300,2.1007,24.0000,666.0,20.2,349.48,24.91,12.00,NaN
478,0.00000,18.1,0.00,0.614,6.185,96.700,2.1705,24.0000,666.0,20.2,379.70,18.03,14.60,NaN
479,0.00000,18.1,0.00,0.614,6.229,88.000,1.9512,24.0000,666.0,20.2,383.32,13.11,21.40,NaN
480,5.82401,0.0,18.10,0.000,0.532,6.242,64.7000,3.4242,24.0,666.0,20.20,396.90,10.74,23.0
481,5.70818,0.0,18.10,0.000,0.532,6.750,74.9000,3.3317,24.0,666.0,20.20,393.07,7.74,23.7
482,5.73116,0.0,18.10,0.000,0.532,7.061,77.0000,3.4106,24.0,666.0,20.20,395.28,7.01,25.0
483,2.81838,0.0,18.10,0.000,0.532,5.762,40.3000,4.0983,24.0,666.0,20.20,392.92,10.42,21.8
484,2.37857,0.0,18.10,0.000,0.583,5.871,41.9000,3.7240,24.0,666.0,20.20,370.73,13.34,20.6
485,3.67367,0.0,18.10,0.000,0.583,6.312,51.9000,3.9917,24.0,666.0,20.20,388.62,10.58,21.2
486,5.69175,0.0,18.10,0.000,0.583,6.114,79.8000,3.5459,24.0,666.0,20.20,392.68,14.98,19.1
487,4.83567,0.0,18.10,0.000,0.583,5.905,53.2000,3.1523,24.0,666.0,20.20,388.22,11.45,20.6
488,0.15086,0.0,27.74,0.000,0.609,5.454,92.7000,1.8209,4.0,711.0,20.10,395.09,18.06,15.2
489,0.18337,0.0,27.74,0.000,0.609,5.414,98.3000,1.7554,4.0,711.0,20.10,344.05,23.97,7.0
490,0.20746,0.0,27.74,0.000,0.609,5.093,98.0000,1.8226,4.0,711.0,20.10,318.43,29.68,8.1
491,0.10574,0.0,27.74,0.000,0.609,5.983,98.8000,1.8681,4.0,711.0,20.10,390.11,18.07,13.6
492,0.11132,0.0,27.74,0.000,0.609,5.983,83.5000,2.1099,4.0,711.0,20.10,396.90,13.35,20.1
493,0.17331,0.0,9.69,0.000,0.585,5.707,54.0000,2.3817,6.0,391.0,19.20,396.90,12.01,21.8
494,0.27957,0.0,9.69,0.000,0.585,5.926,42.6000,2.3817,6.0,391.0,19.20,396.90,13.59,24.5
495,0.17899,0.0,9.69,0.000,0.585,5.670,28.8000,2.7986,6.0,391.0,19.20,393.29,17.60,23.1
496,0.28960,0.0,9.69,0.000,0.585,5.390,72.9000,2.7986,6.0,391.0,19.20,396.90,21.14,19.7
497,0.26838,0.0,9.69,0.000,0.585,5.794,70.6000,2.8927,6.0,391.0,19.20,396.90,14.10,18.3
498,0.23912,0.0,9.69,0.000,0.585,6.019,65.3000,2.4091,6.0,391.0,19.20,396.90,12.92,21.2
499,0.17783,0.0,9.69,0.000,0.585,5.569,73.5000,2.3999,6.0,391.0,19.20,395.77,15.10,17.5
500,0.22438,0.0,9.69,0.000,0.585,6.027,79.7000,2.4982,6.0,391.0,19.20,396.90,14.33,16.8
501,0.06263,0.0,11.93,0.000,0.573,6.593,69.1000,2.4786,1.0,273.0,21.00,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.000,0.573,6.120,76.7000,2.2875,1.0,273.0,21.00,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.000,0.573,6.976,91.0000,2.1675,1.0,273.0,21.00,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.000,0.573,6.794,89.3000,2.3889,1.0,273.0,21.00,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.000,0.573,6.030,80.8000,2.5050,1.0,273.0,21.00,396.90,7.88,11.9

In [51]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz
Requirement already satisfied: numpy in ./machENV/lib/python3.5/site-packages (from pandasql)
Requirement already satisfied: pandas in ./machENV/lib/python3.5/site-packages (from pandasql)
Collecting sqlalchemy (from pandasql)
  Downloading SQLAlchemy-1.1.5.tar.gz (5.1MB)
    100% |████████████████████████████████| 5.1MB 101kB/s ta 0:00:011
Requirement already satisfied: python-dateutil>=2 in ./machENV/lib/python3.5/site-packages (from pandas->pandasql)
Requirement already satisfied: pytz>=2011k in ./machENV/lib/python3.5/site-packages (from pandas->pandasql)
Requirement already satisfied: six>=1.5 in ./machENV/lib/python3.5/site-packages (from python-dateutil>=2->pandas->pandasql)
Installing collected packages: sqlalchemy, pandasql
  Running setup.py install for sqlalchemy ... - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done
  Running setup.py install for pandasql ... - \ done
Successfully installed pandasql-0.7.3 sqlalchemy-1.1.5

In [52]:
import pandasql as sql

In [67]:
fmt = '%b %d, %Y'
finances = {
    "Name": ["Pablo", "Marcel", "Lisa", "Joanne", "Gerry", 'Billy'],
    "Assets": [120000, 80000, 110000, 230000, 1000000, 1200],
    "Debts": [90000, 80000, 30000, 50000, 800000, 10],
    "Updated": [
    datetime.strptime("Jun 10, 2011", fmt),
    datetime.strptime("Dec 30, 2005", fmt),
    datetime.strptime("May 4, 2000", fmt),
    datetime.strptime("Feb 16, 2007", fmt),
    datetime.strptime("Feb 16, 2007", fmt),
    datetime.strptime("Feb 16, 2007", fmt),
    ],
    "Total Rating": [3.5, 2.5, 4.0, 5.0, 2.0, 3.0]
}
fdf = pd.DataFrame(finances)

In [68]:
sql.sqldf('SELECT * FROM fdf GROUP BY [Total Rating]')

    Assets   Debts    Name  Total Rating                     Updated
0  1000000  800000   Gerry           2.0  2007-02-16 00:00:00.000000
1    80000   80000  Marcel           2.5  2005-12-30 00:00:00.000000
2     1200      10   Billy           3.0  2007-02-16 00:00:00.000000
3   120000   90000   Pablo           3.5  2011-06-10 00:00:00.000000
4   110000   30000    Lisa           4.0  2000-05-04 00:00:00.000000
5   230000   50000  Joanne           5.0  2007-02-16 00:00:00.000000